### ISSUE TITLE
ATAK and Heltec Interface Issue

### ISSUE THREAD

**Issue by chaoz014** [meshtastic/ATAK-Plugin#4] opened 2023-12-23 08:09 UTC
Does ATAK create a private channel to send messages?
Whenever I run the 'meshtastic --info' command I do not see any new channels.

I'm basically trying to send text ('hello-world') using the command line and want to know if I can use ATAK to be a receiver for multiple nodes.
meshtastic --sendtext 'hello-world'

Am I able to send Meshtastic messages to ATAK using the plugin? i.e., using Heltec LoRa v3 board to send messages to ATAK via Meshtastic?

Thanks

**Comment by andrekir** [comment] 2024-01-08 02:37
Duplicate of #5

**Closed by andrekir** 2024-01-08 02:37 UTC
